### ISSUE TITLE
puid for Erlang [PORTING]

### ISSUE THREAD

**Issue by yhafri** [puid/Elixir#1]
Hello
Any plan to support `Erlang` or at least make the integration easier in Erlang projects?
Thanks.

**Comment by dingosky** [comment]
The Elixir implementation of **puid** leans heavily on metaprogramming to both produce only the code necessary for the chosen character set and to optimize the character sets provided. I'm not planning on creating an Erlang specific version.

AFAIK, the integration with Erlang projects isn't within the scope of an Elixir library. If there is a way to create an Erlang friendly "bundle" I'm not aware of it.
