### ISSUE TITLE
Comparisons to newer alternatives?

### ISSUE THREAD

**Issue by sondr3** [puid/Elixir#13]
I'm slowly perusing various ID generation algorithms and `puid` looks interesting, but I think the comparisons miss out compared to newer alternatives like [`cuid2`](https://github.com/paralleldrive/cuid2), [`nanoid`](https://github.com/railsmechanic/nanoid) and [`ulid`](https://github.com/ulid/spec) (among others). I'm sure it's quite the task to make these comparisons as you need to dive into different algorithms, but I think it'd be quite valuable.

**Comment by dingosky** [comment]
Commit 491624009c8deff331f96bea4d5bcd06b148dbc5

- cuid2: AFAIKT, there is no Elixir library for version 2 of **cuid**. Version 1 is 7 years old and the notes at that time mentioned it was quite slow.
- nanoid: https://github.com/puid/Elixir#nanoid
- ulid: https://github.com/puid/Elixir#ulid

As a general comment regarding comparisons, **PUID** aims to provide _full control_ of all the key aspects of [random ID generation](https://github.com/puid), as well as provide an intuitive manner of specifying desired ID randomness. I haven't seen any other library that fulfills that specific role.

**Comment by sondr3** [comment]
Thanks a lot 😄
