### ISSUE TITLE
Update Github Releases

### ISSUE THREAD

**Issue by Rio517** [puid/Elixir#14]
![puid_Elixir_ Fast and efficient generation of cryptographically strong probably unique identifiers (puid, aka random string) of specified entropy from various character sets](https://github.com/puid/Elixir/assets/14241/46bad77e-4e35-4b92-bee7-f5eb0573af8f)

GitHub only shows 2.0 release from 2022. 

:)

**Comment by dingosky** [comment]
Fixed. Thanks for the heads-up. I simply overlooked the administrative tasks 🤷🏽‍♂️
