### ISSUE TITLE
undefined function from Misc.Random

### ISSUE THREAD

**Issue by chaodhib** [puid/Elixir#2]
Hello,

First of all, thank you for this nice library!

To the issue itself:
When running the `mix test test/timing.exs`  command, the test case that deals with Misc.Random fails with the following output:

```
  1) test compare to Misc.Random alphanum (TimingTest)
     test/timing.exs:152
     ** (UndefinedFunctionError) function Misc.Random.get_string/1 is undefined or private
     code: time(misc_random, "  Misc.Random (PRNG) ")
     stacktrace:
       (misc_random) Misc.Random.get_string(22)
       test/timing.exs:159: anonymous fn/2 in TimingTest."test compare to Misc.Random alphanum"/1
       (elixir) lib/enum.ex:3003: Enum.reduce_range_inc/4
       test/timing.exs:159: anonymous fn/0 in TimingTest."test compare to Misc.Random alphanum"/1
       (stdlib) timer.erl:166: :timer.tc/1
       test/timing.exs:13: TimingTest.time/2
       test/timing.exs:162: (test)
```

It looks like in a recent release of the dependency (`{:misc_random, "~> 0.2", only: :test}`), `Misc.Random.get_string/1` was [made private](https://github.com/gutschilla/elixir-helper-random/commit/b76a8ba60bd8c61a4a01792493de5efb3c14af44).

**Comment by dingosky** [comment]
Fixed by 4860b5a8

Thanks for the heads up.
