### ISSUE TITLE
Function Puid.Entropy.bits_for_string is missing

### ISSUE THREAD

**Issue by chaodhib** [puid/Elixir#3]
The documentation refers to one function `Puid.Entropy.bits_for_string!/2` but its implementation is missing from the code.

EDIT: looks like the function has been renamed to `bits_for_length`

**Comment by dingosky** [comment]
Fixed by 2acb9926

Note I renamed `bits_for_length` to `bits_for_len` to match the function `len_for_bits`, hence the minor version bump.
