### ISSUE TITLE
Question about seeding

### ISSUE THREAD

**Issue by chaodhib** [puid/Elixir#4]
Hi,

This issue is more a question than an issue really. It is about how Puid should be seeded. As far as I understand, by default, Puid uses `crypto.strong_rand_bytes` under the hood, which is already seeded. So, as a Puid user, nothing has to be done in that regard. Is that correct?

Also, [the documentation](https://erlang.org/doc/man/crypto.html#strong_rand_bytes-1) mentions that the function can raise an exception `error:low_entropy`. As a Puid user, how should this situation be handled?

Thanks.

**Comment by dingosky** [comment]
In general, if you are using the default entropy generator `:crypto.strong_rand_bytes` then all caveats regarding the use of that function are in play, including seeding and the possibility of a `low_entropy` error.

See this [stackoverflow entry](https://stackoverflow.com/questions/30650842/how-to-handle-low-entropy-exception-of-cryptostrong-rand-bytesn) for a discussion of `:crypto.strong_rand_bytes` usage.

It is worth noting that `puid` uses the randomly generated bits as efficiently as possible. Most (all?) other libraries are either simply throwing away bits or wasting bits in the sense that more entropy is being consumed than necessary. So although `puid` doesn't solve the concerns raised by using `:crypto.strong_rand_bytes` it does at least keep you from implicitly overusing that function and thereby increasing the risk of low entropy.

Finally, `puid` allows the user to specify a custom source for the randomly generated bytes. If you find a generator that more closely solves your needs as an entropy source, you can specify a function to use that source when defining your `puid` module by using the `rand_bytes` option.
