### ISSUE TITLE
Changelog Request and missing release tags

### ISSUE THREAD

**Issue by Rio517** [puid/Elixir#5]
Hello!  

This looks like a great project and your comprehensive readme persuaded me to apply this to our current project! I have two small requests that might even help increase adoption. 

* Perhaps add a changelog
* Would you mind creating release tags for the most releases 1.1.x - would be nice if GitHub release matched what's on hexpm. 

Thanks and good luck!

**Comment by dingosky** [comment]
Thx for the suggestions. I will add a changelog in the near future as I want to update the status of this package versus the various other solutions that I compare with in the documentation. Also, I created a release tag for the latest slight changes (1.1.2). I just completely overlooked those tags weren't being pushed to origin 🤦🏼‍♂️

**Comment by dingosky** [comment]
Addressed in 2.0.0
